import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Hls from 'hls.js';
import { ArrowLeft, Check, Loader2, Pause, Play, Settings2, Volume2, VolumeX } from 'lucide-react';
import { saveProgress } from '../api/history';
import { detectStreamType, generateUniversalServers } from '../utils/streamingEngines';

export function TVPlayer({ item, server, onClose }) {
  const videoRef = useRef(null); const hlsRef = useRef(null); const timerRef = useRef(null); const retriesRef = useRef(0);
  const [sourceIndex, setSourceIndex] = useState(0); const [playing, setPlaying] = useState(false); const [buffering, setBuffering] = useState(true); const [muted, setMuted] = useState(false); const [error, setError] = useState(''); const [settings, setSettings] = useState(false); const [levels, setLevels] = useState([]); const [level, setLevel] = useState(-1); const [time, setTime] = useState(0); const [duration, setDuration] = useState(0);
  const isLive = Boolean(item?.is_live || item?.type === 'live' || item?.year === 'LIVE');
  const sources = useMemo(() => generateUniversalServers({ ...item, players: [...(Array.isArray(item?.players) ? item.players : Array.isArray(item?.player) ? item.player : []), ...(server ? [server] : [])] }), [item, server]);
  const active = sources[sourceIndex];
  const clearTimer = () => { if (timerRef.current) clearTimeout(timerRef.current); timerRef.current = null; };
  const fail = useCallback(message => { clearTimer(); if (sourceIndex + 1 < sources.length) { setError(`${message} Trying source ${sourceIndex + 2}.`); setSourceIndex(value => value + 1); } else { setBuffering(false); setError('This stream is unavailable right now.'); } }, [sourceIndex, sources.length]);
  const arm = useCallback((delay, message) => { clearTimer(); timerRef.current = setTimeout(() => fail(message), delay); }, [fail]);
  useEffect(() => { setSourceIndex(0); setError(''); }, [item?.id]);

  useEffect(() => {
    const video = videoRef.current; if (!video || !active?.url) { setBuffering(false); setError('No checked stream is available for this title.'); return; }
    let disposed = false; retriesRef.current = 0; setBuffering(true); setError(''); setLevels([]); arm(15000, 'The stream took too long to start.');
    const play = () => video.play().then(() => { if (!disposed) { setPlaying(true); setBuffering(false); clearTimer(); } }).catch(() => setPlaying(false));
    const type = detectStreamType(active.url, active.type || active.source);
    if (type === 'hls' && Hls.isSupported()) {
      const hls = new Hls({ enableWorker: true, startLevel: -1, capLevelToPlayerSize: true, testBandwidth: true, abrEwmaDefaultEstimate: 2500000, abrBandWidthFactor: .8, abrBandWidthUpFactor: .65, maxBufferLength: isLive ? 20 : 45, maxMaxBufferLength: isLive ? 35 : 75, backBufferLength: isLive ? 10 : 30, lowLatencyMode: false, manifestLoadingTimeOut: 10000, manifestLoadingMaxRetry: 2, levelLoadingMaxRetry: 2, fragLoadingTimeOut: 15000, fragLoadingMaxRetry: 3, xhrSetup: xhr => Object.entries(active.headers || {}).forEach(([name,value]) => { try { xhr.setRequestHeader(name,value); } catch {} }) });
      hlsRef.current = hls; hls.attachMedia(video); hls.loadSource(active.url);
      hls.on(Hls.Events.MANIFEST_PARSED, (_, data) => { setLevels((data.levels || []).map((entry,index) => ({ index, label: entry.height ? `${entry.height}p` : `${Math.round(entry.bitrate / 1000)} kbps` }))); play(); });
      hls.on(Hls.Events.ERROR, (_, data) => { if (!data.fatal) return; retriesRef.current += 1; if (retriesRef.current <= 2 && data.type === Hls.ErrorTypes.NETWORK_ERROR) return hls.startLoad(); if (retriesRef.current <= 2 && data.type === Hls.ErrorTypes.MEDIA_ERROR) return hls.recoverMediaError(); fail('Playback failed.'); });
    } else { video.src = active.url; video.load(); play(); }
    const waiting = () => { setBuffering(true); arm(10000, 'Playback stalled.'); }; const started = () => { setPlaying(true); setBuffering(false); setError(''); clearTimer(); }; const paused = () => setPlaying(false); const failed = () => fail('The device could not play this source.'); const updated = () => { setTime(video.currentTime || 0); setDuration(Number.isFinite(video.duration) ? video.duration : 0); };
    video.addEventListener('waiting', waiting); video.addEventListener('playing', started); video.addEventListener('pause', paused); video.addEventListener('error', failed); video.addEventListener('timeupdate', updated);
    return () => { disposed = true; clearTimer(); video.removeEventListener('waiting', waiting); video.removeEventListener('playing', started); video.removeEventListener('pause', paused); video.removeEventListener('error', failed); video.removeEventListener('timeupdate', updated); if (hlsRef.current) hlsRef.current.destroy(); hlsRef.current = null; video.removeAttribute('src'); video.load(); };
  }, [active?.url]);

  const close = useCallback(() => { if (!isLive && duration > 0) saveProgress(item,time,duration); onClose?.(time,duration); }, [duration,isLive,item,onClose,time]);
  const toggle = () => { const video = videoRef.current; if (!video) return; video.paused ? video.play().catch(() => {}) : video.pause(); };
  useEffect(() => { const keys = event => { if (['Escape','GoBack','Backspace'].includes(event.key)) { event.preventDefault(); close(); } else if (['Enter',' '].includes(event.key)) { event.preventDefault(); toggle(); } else if (!isLive && event.key === 'ArrowRight' && videoRef.current) videoRef.current.currentTime += 10; else if (!isLive && event.key === 'ArrowLeft' && videoRef.current) videoRef.current.currentTime = Math.max(0,videoRef.current.currentTime - 10); }; window.addEventListener('keydown',keys,true); return () => window.removeEventListener('keydown',keys,true); }, [close,isLive]);
  const selectLevel = value => { setLevel(value); if (hlsRef.current) hlsRef.current.currentLevel = value; };

  return <div className="tv-player-container" style={{position:'fixed',inset:0,zIndex:10000,background:'#000'}}><video ref={videoRef} playsInline poster={item?.backdrop_url || item?.poster_url || ''} style={{width:'100%',height:'100%',objectFit:'contain'}}/><div className="player-osd" style={{position:'absolute',inset:0,padding:32,display:'flex',flexDirection:'column',justifyContent:'space-between',background:'linear-gradient(180deg,rgba(0,0,0,.8),transparent 40%,rgba(0,0,0,.85))'}}><div style={{display:'flex',gap:18,alignItems:'center'}}><button className="player-btn" data-focusable="true" onClick={close}><ArrowLeft/></button><div><strong>{item?.title_en || item?.title}</strong><div style={{opacity:.7}}>{active?.name || 'Source'}</div></div></div>{buffering && <div style={{alignSelf:'center',display:'flex',gap:10}}><Loader2 className="spin-animation"/>Loading stream…</div>}{error && <div style={{alignSelf:'center',padding:14,background:'rgba(127,29,29,.94)',borderRadius:8}}>{error}</div>}<div><div style={{display:'flex',alignItems:'center',gap:14}}><button className="player-btn" data-focusable="true" onClick={toggle}>{playing?<Pause/>:<Play/>}</button><button className="player-btn" data-focusable="true" onClick={() => { if(videoRef.current){videoRef.current.muted=!videoRef.current.muted;setMuted(videoRef.current.muted);} }}>{muted?<VolumeX/>:<Volume2/>}</button><button className="player-btn" data-focusable="true" onClick={() => setSettings(value=>!value)}><Settings2/></button><span style={{marginLeft:'auto'}}>{isLive?'LIVE':`${Math.floor(time/60)}:${String(Math.floor(time%60)).padStart(2,'0')} / ${Math.floor(duration/60)}:${String(Math.floor(duration%60)).padStart(2,'0')}`}</span></div>{settings && <div style={{marginTop:14,padding:16,background:'rgba(15,23,42,.97)',borderRadius:10}}><div>Quality</div><button data-focusable="true" onClick={() => selectLevel(-1)}>Auto {level===-1&&<Check size={14}/>}</button>{levels.map(entry=><button data-focusable="true" key={entry.index} onClick={() => selectLevel(entry.index)}>{entry.label} {level===entry.index&&<Check size={14}/>}</button>)}{sources.length>1&&<><div style={{marginTop:12}}>Sources</div>{sources.map((entry,index)=><button data-focusable="true" key={entry.id} onClick={() => setSourceIndex(index)}>{entry.name} {sourceIndex===index&&<Check size={14}/>}</button>)}</>}</div>}</div></div></div>;
}
