import { isFavoriteChannel } from './history.js';
import { isSafeHttpUrl } from '../utils/streamingEngines.js';

export const CURATED_HD_CHANNELS = [];
const CACHE_KEY = 'ajo_iptv_cache_v2';
const CUSTOM_KEY = 'ajo_custom_m3u_v2';
const JIOTV_KEY = 'ajo_jiotv_host_v2';
const CACHE_TTL = 30 * 60 * 1000;
const PLAYLISTS = ['https://iptv-org.github.io/iptv/countries/in.m3u','https://raw.githubusercontent.com/Free-TV/IPTV/master/playlists/playlist_in.m3u'];
async function fetchText(url, timeout = 8000) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeout); try { const response = await fetch(url, { signal: controller.signal, cache: 'no-store' }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return await response.text(); } finally { clearTimeout(timer); } }
export function normalizeChannelItem(channel, index = 0) { if (!channel?.url || !isSafeHttpUrl(channel.url)) return null; const title = channel.title || channel.name || `Channel ${index + 1}`; const item = { id: channel.id || `channel-${index + 1}`, title, title_en: title, category: channel.category || 'Live TV', poster: channel.poster || channel.poster_url || '', poster_url: channel.poster_url || channel.poster || '', url: channel.url, is_live: true, type: 'live', year: 'LIVE', provider: channel.provider || null, players: [{ name: channel.quality || 'Auto', url: channel.url, source: 'hls', quality: channel.quality || null, headers: channel.headers || {} }] }; item.player = item.players; item.is_favorite = isFavoriteChannel(item); return item; }
export function parseM3U(content) { if (!content) return []; const channels = []; let pending = null; for (const raw of content.split(/\r?\n/)) { const line = raw.trim(); if (line.startsWith('#EXTINF:')) { const attr = name => line.match(new RegExp(name + '="([^"]*)"', 'i'))?.[1] || ''; pending = { id: attr('tvg-id'), poster: attr('tvg-logo'), category: attr('group-title') || 'Live TV', title: line.slice(line.lastIndexOf(',') + 1).trim() }; } else if (pending && /^https?:\/\//i.test(line)) { pending.url = line; channels.push(pending); pending = null; } } return channels; }
function readCache() { try { const value = JSON.parse(localStorage.getItem(CACHE_KEY) || 'null'); return value && Date.now() - value.savedAt < CACHE_TTL && Array.isArray(value.items) ? value.items : null; } catch { return null; } }
export async function getIPTVChannels() { const cached = readCache(); if (cached) return cached; const custom = localStorage.getItem(CUSTOM_KEY); const urls = [...(custom && isSafeHttpUrl(custom) ? [custom] : []), ...PLAYLISTS]; const results = await Promise.allSettled(urls.map(url => fetchText(url))); const seen = new Set(); const items = []; for (const result of results) { if (result.status !== 'fulfilled') continue; for (const channel of parseM3U(result.value)) { const normalized = normalizeChannelItem(channel, items.length); const key = (normalized?.id || normalized?.title || '').toLowerCase(); if (!normalized || !key || seen.has(key)) continue; seen.add(key); items.push(normalized); } } if (items.length) localStorage.setItem(CACHE_KEY, JSON.stringify({ savedAt: Date.now(), items })); return items; }
export async function getJioTVServerChannels(serverHost) { const host = String(serverHost || localStorage.getItem(JIOTV_KEY) || '').replace(/\/$/, ''); if (!host || !isSafeHttpUrl(host)) return []; try { return parseM3U(await fetchText(host + '/playlist.m3u')).map(normalizeChannelItem).filter(Boolean); } catch { return []; } }
export function saveIPTVConfig({ customM3uUrl, jioTvHost }) { if (customM3uUrl !== undefined) localStorage.setItem(CUSTOM_KEY, customM3uUrl || ''); if (jioTvHost !== undefined) localStorage.setItem(JIOTV_KEY, jioTvHost || ''); localStorage.removeItem(CACHE_KEY); }
export function getIPTVConfig() { return { customM3uUrl: localStorage.getItem(CUSTOM_KEY) || '', jioTvHost: localStorage.getItem(JIOTV_KEY) || '' }; }
