import { getIPTVChannels } from './iptv.js';
import { generateUniversalServers } from '../utils/streamingEngines.js';
const BASE_URL = 'https://mapi.elochkaigolochla.com/api/v1';
const CACHE_KEY = 'ajo_catalog_v2'; const CACHE_TTL = 30 * 60 * 1000; let memoryCatalog = null;
async function fetchJson(url, timeout = 8000) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeout); try { const response = await fetch(url, { signal: controller.signal, headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return await response.json(); } finally { clearTimeout(timer); } }
export function normalizeMediaItem(item, category = 'movie') { if (!item) return null; const live = category === 'live' || item.is_live || item.type === 'live' || item.type === 'broadcast' || item.year === 'LIVE'; const title = item.title_en || item.title || item.title_ru || item.name; if (!title) return null; const sources = generateUniversalServers(item); if (!sources.length) return null; const poster = item.poster_url || item.poster || item.logo || item.image || item.thumbnail || ''; return { ...item, id: item.id || item.tmdb_id || item.kinopoisk_id || item.movie_id || `${category}:${title}`, title, title_en: title, poster, poster_url: poster, backdrop_url: item.backdrop_url || poster, url: sources[0].url, stream_url: sources[0].url, is_live: live, type: live ? 'live' : (item.type || category), category: item.category || category, players: sources, player: sources, ratings: item.ratings || null, genres: Array.isArray(item.genres) ? item.genres : [], year: item.year || null, duration: item.duration || null, description: item.description || '', provider: item.provider || item.network || null }; }
function readCachedCatalog() { if (memoryCatalog) return memoryCatalog; try { const cached = JSON.parse(localStorage.getItem(CACHE_KEY) || 'null'); if (cached && Date.now() - cached.savedAt < CACHE_TTL) return (memoryCatalog = cached.data); } catch {} return null; }
async function loadCatalog() { const cached = readCachedCatalog(); if (cached) return cached; const payload = await fetchJson(BASE_URL + '/catalog'); const sections = payload?.result?.full || payload?.full || []; const result = { all: [], bollywood: [], hollywood: [], serials: [] }; const seen = new Set(); for (const section of sections) { const sectionName = String(section.name || '').toLowerCase(); for (const raw of section.movies || section.items || []) { const category = sectionName.includes('hollywood') ? 'hollywood' : sectionName.includes('series') || sectionName.includes('serial') ? 'serials' : 'bollywood'; const item = normalizeMediaItem(raw, category); const key = item ? String(item.id) + ':' + item.url : ''; if (!item || seen.has(key)) continue; seen.add(key); result.all.push(item); result[category].push(item); } } memoryCatalog = result; try { localStorage.setItem(CACHE_KEY, JSON.stringify({ savedAt: Date.now(), data: result })); } catch {} return result; }
export async function getLiveBroadcasts() { const groups = await Promise.allSettled([fetchJson(BASE_URL + '/new-broadcasts'), getIPTVChannels()]); const raw = []; if (groups[0].status === 'fulfilled') raw.push(...(Array.isArray(groups[0].value) ? groups[0].value : groups[0].value?.results || groups[0].value?.result || [])); if (groups[1].status === 'fulfilled') raw.push(...groups[1].value); const seen = new Set(); return raw.flatMap(entry => { const item = normalizeMediaItem(entry, 'live'); const key = (item?.id || item?.title || '').toString().toLowerCase(); if (!item || !key || seen.has(key)) return []; seen.add(key); return [item]; }); }
export async function getBollywoodCatalog() { try { return (await loadCatalog()).bollywood; } catch { return []; } }
export async function getHollywoodCatalog() { try { return (await loadCatalog()).hollywood; } catch { return []; } }
export async function getSerialsCatalog() { try { return (await loadCatalog()).serials; } catch { return []; } }
export async function searchAllMedia(query) { const clean = String(query || '').trim().toLowerCase(); if (!clean) return []; const [catalog, live] = await Promise.allSettled([loadCatalog(), getLiveBroadcasts()]); const items = [...(catalog.status === 'fulfilled' ? catalog.value.all : []), ...(live.status === 'fulfilled' ? live.value : [])]; const seen = new Set(); return items.filter(item => { const hit = `${item.title} ${item.category || ''}`.toLowerCase().includes(clean); const key = String(item.id); if (!hit || seen.has(key)) return false; seen.add(key); return true; }); }
export async function getSeriesEpisodes(movieId) { if (!movieId) return []; try { const data = await fetchJson(BASE_URL + '/serial/episodes/' + encodeURIComponent(movieId)); const raw = Array.isArray(data) ? data : data?.results || data?.result || []; return raw.flatMap((episode, index) => { const sources = generateUniversalServers(episode); return sources.length ? [{ ...episode, id: episode.id || `${movieId}:${index + 1}`, episode: episode.episode || index + 1, players: sources, player: sources, url: sources[0].url }] : []; }); } catch { return []; } }
export function getFallbackLiveChannels() { return []; }
export function getFallbackCatalog() { return []; }
